### ISSUE TITLE
Pal Crystal correct frequency.

### ISSUE THREAD

**Issue by amazzanti** [SukkoPera/OpenVideoModulator#1]
Hi,

here to remind you the Pal Crystal frequency is 4.433619MHZ.

Thanks,

Antonio

**Comment by snnsyhn** [comment]
Hello Antonio
My name is Sinan
I want to use your “OpenC64KernalCart V1” in my project if you let me.
https://www.pcbway.com/project/shareproject/OpenC64KernalCart_V1.html
My regads 
Sinan
From: Antonio Mazzanti 
Sent: Wednesday, April 29, 2020 4:12 PM
To: SukkoPera/OpenVideoModulator 
Cc: Subscribed 
Subject: [SukkoPera/OpenVideoModulator] Pal Crystal correct frequency. (#1)
Hi,

here to remind you the Pal Crystal frequency is 4.433619MHZ.

Thanks,

Antonio

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/SukkoPera/OpenVideoModulator/issues/1", "url": "https://github.com/SukkoPera/OpenVideoModulator/issues/1", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
