### ISSUE TITLE
Doesn't appear to work with NTSC?

### ISSUE THREAD

**Issue by GK6475** [SukkoPera/OpenVideoModulator#5]
Hi, so I soldered everything onto the board appropriately with NTSC configuration, but the signal coming out is very messy. The luma and sync show up to some extent, but the chroma is very unstable and flashes constantly. I've tried using RGB from a Sega Genesis, which I know works normally, and also from my computer with CRT emudriver. Both produced the same results. How can I fix this issue?

Video of issue:
https://drive.google.com/file/d/1a7pYuHD8HxAwpXQZXlm3o_29vsbsfbSq/view?usp=sharing

**Comment by SukkoPera** [comment]
Since I live in Europe, I have never used the NTSC configuration, but I think others did with success.

Some random hints:
- Make sure the crystal is the right frequency: you need 3.579545 MHz for NTSC.
- Different crystals might need different values of C1: generally something between 12 and 22 pF works but you should really check the datasheet for your crystal.
- Make sure to use at least 10 uF at C6, 100 uF is better.
- Finally, I think there's a bad batch of AD724 chips around, if you bought it from China: I have had similar issues with the last few I bought, but chips from an earlier purchase worked fine. I don't know if they have a manufacturing fault, require a different crystal or whatever, but they only work well if I physically TOUCH che crystal while the machine is on. This suggests an issue with C1 but I haven't been able to get them to work reliably yet. (See #4)

Good luck!

**Comment by GK6475** [comment]
This is the datasheet for my crystal:
https://www.mouser.com/datasheet/2/3/ab-1499141.pdf
https://www.mouser.com/ProductDetail/815-AB-3.579545-B2

Seems like 10 pF on C1 should work to some extent. Any advice? Also, what AD724 chips would you recommend buying, and from where? Most sites sell them for $20 a piece, which is a bit expensive.

**Comment by SukkoPera** [comment]
You might actually want to try higher values, as high as 18 pF.

I know original AD724s are not cheap but well, there might be a reason for that ;). I can't really recommend any, I've been lucky enough to find a Chinese batch that is working and I have just used those so far.

**Comment by GK6475** [comment]
Ah, well I tried 20pF, but that didn't change much. Guess I'll have to find a better source of AD724s. Also, what do your working chips look like on top? Can you send a picture? I've seen some different styles of AD724s and want to narrow my search somewhat.

**Comment by GK6475** [comment]
Came back to this over a year later, and it was just my sync signal the whole time. Apparently the AD724 doesn't like 75 ohm CSYNC, and prefers TTL (LM1881 works great with it). Heh, I guess now I can make 10-20 of these since I bought a few different packs of chips.
